// Handles reserved from user assignment. Comparison is case-insensitive.
// Source: docs/policies.md §2.
export const RESERVED_HANDLES: ReadonlySet<string> = new Set([
  'admin',
  'api',
  'support',
  'help',
  'www',
  'settings',
  'auth',
  'login',
  'register',
  'profile',
  'calls',
  'wallet',
  'notifications',
  'legal',
  'eula',
  'privacy',
  'terms',
  'ohlify',
  'app',
  'mobile',
  'web',
  'static',
  'public',
  'cdn',
  'me',
  'onboarding',
  'home',
  'professionals',
  'feedback',
  'rating',
  'banks',
  'payments',
  'webhooks',
  'health',
  'docs',
  'about',
  'contact',
  'pricing',
  'blog',
  'news',
  'press',
  'jobs',
  'careers',
  'privacy_policy',
  'tos',
]);

export const HANDLE_REGEX = /^[a-z0-9_]{3,24}$/;
