/**
 * Icon proxy. Every consumer — primitives, domain widgets, modals, shell,
 * feature code in apps — imports icons from here, never from `lucide-react`
 * directly. Swapping icon libraries later is a one-file change.
 *
 * Naming convention: `Icon<Name>` where Name comes from the underlying lib.
 * `LucideIcon` is re-exported so consumers can type a generic icon prop.
 */
export type { LucideIcon } from 'lucide-react';

export {
  ArrowLeft as IconBack,
  ArrowRight as IconArrowRight,
  Bell as IconBell,
  Briefcase as IconBriefcase,
  Building2 as IconBuilding,
  CalendarDays as IconCalendar,
  Calendar as IconCalendarDay,
  Check as IconCheck,
  CheckCircle2 as IconCheckCircle,
  ChevronDown as IconChevronDown,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  CircleAlert as IconAlertCircle,
  CircleHelp as IconHelpCircle,
  Clock as IconClock,
  Copy as IconCopy,
  CreditCard as IconCreditCard,
  Eye as IconEye,
  EyeOff as IconEyeOff,
  FileText as IconFileText,
  Filter as IconFilter,
  Heart as IconHeart,
  HelpCircle as IconHelp,
  Home as IconHome,
  IdCard as IconIdCard,
  Info as IconInfo,
  Lock as IconLock,
  LogOut as IconLogout,
  Mail as IconMail,
  MessageCircle as IconChat,
  Mic as IconMic,
  MicOff as IconMicOff,
  PanelsTopLeft as IconComponents,
  Phone as IconPhone,
  PhoneCall as IconPhoneCall,
  PhoneIncoming as IconPhoneIncoming,
  PhoneOff as IconPhoneOff,
  Plus as IconPlus,
  Search as IconSearch,
  Send as IconSend,
  Settings as IconSettings,
  Shield as IconShield,
  Sparkles as IconSparkles,
  Star as IconStar,
  Tag as IconTag,
  Trash2 as IconDelete,
  TriangleAlert as IconAlertTriangle,
  Upload as IconUpload,
  User as IconUser,
  Users as IconUsers,
  Video as IconVideo,
  VideoOff as IconVideoOff,
  Volume2 as IconVolume,
  VolumeX as IconVolumeOff,
  Wallet as IconWallet,
  X as IconClose,
} from 'lucide-react';
