#!/usr/bin/env node
/**
 * Generates the Hawk gallery registry.
 *
 * Walks `apps/admin-web/src/features/hawk-preview/parts/page-*.tsx`, reads the
 * `@HawkPage` docblock above each exported page component, and rewrites
 * `hawk-pages.generated.ts`.
 *
 * A component that exists but is not in the gallery is a component nobody
 * reviews. The design system's own `repatch.py` exists for the same reason, and
 * the Flutter port's `tool/hawk_pages.py` is the direct counterpart.
 *
 * Run from the repo root:  node tools/hawk-pages.mjs
 * Check without writing:   node tools/hawk-pages.mjs --check
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const partsDir = join(root, 'apps/admin-web/src/features/hawk-preview/parts');
const outFile = join(partsDir, 'hawk-pages.generated.ts');

/**
 * Matches a docblock carrying `@HawkPage`, optionally `@HawkStates`, followed
 * by the exported function it documents.
 */
const PAGE = /\/\*\*[\s\S]*?@HawkPage\s+([^\n*]+)[\s\S]*?\*\/\s*export function (\w+)/g;
const STATES = /@HawkStates\s+([^\n*]+)/;

/** Parses `slug=20-button name=Button group=Actions` into an object. */
function parseAttributes(line) {
  const attributes = {};
  // Values may contain spaces ("Data display"), so split on the next key rather
  // than on whitespace.
  const pattern = /(\w+)=(.*?)(?=\s+\w+=|$)/g;
  let match;
  while ((match = pattern.exec(line.trim())) !== null) {
    attributes[match[1]] = match[2].trim();
  }
  return attributes;
}

const files = readdirSync(partsDir)
  .filter((name) => name.startsWith('page-') && name.endsWith('.tsx'))
  .sort();

const pages = [];

for (const file of files) {
  const source = readFileSync(join(partsDir, file), 'utf8');
  let match;
  while ((match = PAGE.exec(source)) !== null) {
    const [block, attributeLine, component] = match;
    const attributes = parseAttributes(attributeLine);
    const states = STATES.exec(block);

    if (!attributes.slug || !attributes.name || !attributes.group) {
      throw new Error(
        `${file}: ${component} has an @HawkPage docblock missing slug, name or group.`,
      );
    }

    pages.push({
      slug: attributes.slug,
      name: attributes.name,
      group: attributes.group,
      states: states ? states[1].trim().split(/\s+/) : [],
      component,
      module: `./${file.replace(/\.tsx$/, '.js')}`,
    });
  }
}

const duplicates = pages
  .map((page) => page.slug)
  .filter((slug, index, all) => all.indexOf(slug) !== index);
if (duplicates.length > 0) {
  throw new Error(`Duplicate page slugs make search ambiguous: ${duplicates.join(', ')}`);
}

// Group imports by module so the generated file has one import per file.
const byModule = new Map();
for (const page of pages) {
  if (!byModule.has(page.module)) byModule.set(page.module, []);
  byModule.get(page.module).push(page.component);
}

const imports = [...byModule.entries()]
  .map(([module, components]) => `import { ${components.sort().join(', ')} } from '${module}';`)
  .join('\n');

const entries = pages
  .map(
    (page) => `  {
    slug: ${JSON.stringify(page.slug)},
    name: ${JSON.stringify(page.name)},
    group: ${JSON.stringify(page.group)},
    states: ${JSON.stringify(page.states)},
    component: ${page.component},
  },`,
  )
  .join('\n');

const output = `// GENERATED BY tools/hawk-pages.mjs — DO NOT EDIT BY HAND.
//
// Rebuild with:  node tools/hawk-pages.mjs
//
// Every page declares itself in an @HawkPage docblock. A component that exists
// but is not in the gallery is a component nobody reviews.

import type { HawkPageEntry } from './registry.js';

${imports}

export const HAWK_PAGES: readonly HawkPageEntry[] = [
${entries}
];
`;

if (process.argv.includes('--check')) {
  const current = (() => {
    try {
      return readFileSync(outFile, 'utf8');
    } catch {
      return '';
    }
  })();
  if (current !== output) {
    console.error('hawk-pages.generated.ts is stale — run: node tools/hawk-pages.mjs');
    process.exit(1);
  }
  console.log(`hawk-pages.generated.ts is in sync (${pages.length} pages).`);
  process.exit(0);
}

writeFileSync(outFile, output);
console.log(`Wrote ${pages.length} pages across ${byModule.size} files.`);
